#!/usr/bin/env python
#
#
# $Id$
# $Author$
# $Date$
#
# Original author Rob Kutschke.
#

import os, re
Import('env')

Import('mu2e_helper')

helper=mu2e_helper()

rootlibs = env['ROOTLIBS']

mylibs=[
    'art_Framework_Core',
    'art_Framework_Services_Optional_TFileService_service',
    'MuCapDataProducts',
    'Mu2eInterfaces',
    'Mu2eUtilities',
    'CLHEP'
    ] + rootlibs

mainlib = helper.make_mainlib ( mylibs )

helper.make_plugins( [ mainlib, mylibs ] )

#helper.make_dict_and_map( [ mainlib, ] )

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
