#!/usr/bin/env python
#
#
# $Id$
# $Author$
# $Date$
#
# Original author Rob Kutschke.
#

import os
Import('env')
Import('mu2e_helper')

helper=mu2e_helper();

mainlib = helper.make_mainlib ( [ 'art_Framework_Core', 'CLHEP'] )

helper.make_plugins( [ mainlib, ] )

helper.make_dict_and_map( [ mainlib, 'art_Framework_Core', 'CLHEP', ] )

# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
